// Generated by scripts/generate-runtime-config.mjs — do not edit by hand.
export const runtimeConfig = {
  backendUrl: "https://api-community.mlptf.org.my/",
  backendGraphqlUrl: "https://api-community.mlptf.org.my/graphql/",
  mapboxToken:
    "pk.eyJ1Ijoia3dvbmd0biIsImEiOiJjbHd3eGIxazEwd2tsMm5yM3NyYmt4b2s4In0.l1ThIQzGXxoPDY3VyMtC-Q",
  captchaSiteKey: "6Le4ekQhAAAAAKu_C7LTyylJfe8Q8Gv5fiNFx_kj",
  environmentName: "production",
  uploadConcurrency: 5,
};
