// Build information, automatically generated by `ng-info`
const build = {
    version: "0.0.0",
    timestamp: (new Date()).toISOString(),
    message: null,
    git: {
        user: "Kwong Tung Nan",
        branch: "dev",
        hash: "<<This is a test build>>",
        fullHash: "<<This is a test build>>"
    }
};

export default build;
