// Build information, automatically generated by `ng-info`
const build = {
    version: "0.0.0",
    timestamp: "Mon Jul 25 2022 21:29:32 GMT+0800 (Malaysia Time)",
    message: null,
    git: {
        user: "Kwong Tung Nan",
        branch: "main",
        hash: "201626",
        fullHash: "20162662cca95b5d1024db7c81ccc1878daaf118",
    },
};

export default build;
